apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: web-app
          image: gcr.io/upe-projects/web-app@sha256:47097f2d51e3d93e8b0fed70b9bbcd678435bbd6c070be624d86796633a53db1
          ports:
            - containerPort: 8080
