---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "web-app"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        deployment: "hello"
  spec:
    containers:
      - name: "web-app-sha256"
        image: "gcr.io/upe-projects/web-app@sha256:$GITHUB_SHA"
        command: ["npm", "start"]
        ports:
          - containerPort: 8080
