apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: "gcr.io/upe-projects/web-app@sha256:${{ github.sha }}"
          ports:
            - containerPort: 8080
