apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-app-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: web-app-service
              servicePort: 80
