---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
    name: "web-app"
    namespace: "default"
    labels:
    app: "web-app"
spec:
    replicas: 3
    selector:
    matchLabels:
    app: "web-app"
    template:
    metadata:
    labels:
    app: "web-app"
    spec:
    containers:
        - name: "web-app-sha256"
    image: "gcr.io/upe-projects/web-app@sha256:$GITHUB_SHA"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
    name: "web-app-hpa"
    namespace: "default"
    labels:
    app: "web-app"
spec:
    scaleTargetRef:
    kind: "Deployment"
    name: "web-app"
    apiVersion: "apps/v1"
    minReplicas: 1
    maxReplicas: 5
    metrics:
    - type: "Resource"
    resource:
    name: "cpu"
    targetAverageUtilization: 80
    